# Generated by Django 4.2.6 on 2023-10-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "referenceno",
                    models.CharField(
                        help_text="referenceno",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("mobileno", models.IntegerField()),
            ],
        ),
    ]
